
version: '3.7'
services:
    app:
        build: app
        volumes:
            - .:/code 
    nginx:
        build: nginx
        ports: 
            - "80:80"   
        depends_on:
          - app
