version: '2'
services:
    web:
        build: .
        ports:
            - "5001:5000"
        volumes:
            - .:/code
    nginx:
        build: .
        ports: 
            - "8080:8080"   
        depends_on:
        - web
