
- name : Playbook_test
  hosts: node02
  remote_user: vagrant
  tasks:
  - name: stop nginx
    shell: "sudo service nginx stop"
    become: 'yes'
  - name: stat AppFlask
    stat: 
      path: /home/vagrant/AppFlask
    register: foo
  - name: suppresion docker
    shell: "cd AppFlask; sudo docker compose down; sudo docker system prune --all -f && sudo docker kill $(sudo docker ps -q) && sudo docker rm $(sudo docker ps -a -q) && sudo docker rmi $(sudo docker imag$
    when: foo.stat.exists
    become: 'yes' 
  - name: suppresion repo Appflask
    file:
      state: absent
      path: /home/vagrant/AppFlask/
    when: foo.stats.exists    
  - name: installation python & outils
    apt: 
     name:
        - python3-pip
        - python3
        - curl
        - ca-certificates
        - software-properties-common
        - lsb-release
        - gnupg
        - libseccomp2
        - build-essential
        - apt-transport-https
     state: latest
    become: 'yes'
  - name: Add Docker GPG apt Key
    apt_key:
       url: https://download.docker.com/linux/debian/gpg
       state: present
    become: 'yes'
  - name: Add Docker Repository
    command: "sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable' "
    become: 'yes'
  - name: Update apt and install docker-ce
    apt:
      name: 
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
      state: latest
      update_cache: true
    become: 'yes'
  - name: clone git
    git:
      repo: https://github.com/NaimAssoumani/Projets_Devops_flask
      dest: /home/vagrant/AppFlask
      version: preprod
      clone: yes
      update: no
  - name: suppresion docker
    shell: "cd AppFlask; sudo docker compose down; sudo docker system prune --all -f && sudo docker kill $(sudo docker ps -q) && sudo docker rm $(sudo docker ps -a -q) && sudo docker rmi $(sudo docker images -q)"
    become: 'yes'

  - name: docker compose
    shell: "cd AppFlask; sudo docker compose up --build -d --scale app=3
"
    become: 'yes'
