
- name : Playbook_test
  hosts: node02
  remote_user: vagrant
  tasks:
  - name: vider repo
    shell: " rm /home/vagrant/AppFlask -rf"
    become: 'yes'
  - name: installation python & outils
    apt: 
     name:
        - python3-pip
        - python3
        - curl
        - ca-certificates
        - software-properties-common
        - lsb-release
        - gnupg
        - libseccomp2
        - build-essential
        - apt-transport-https
     state: latest
    become: 'yes'
  - name: Add Docker GPG apt Key
    shell: "sudo mkdir -p /etc/apt/keyrings; curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
    become: 'yes'
  - name: Add Docker Repository
    apt_repository:
    shell: "echo \
  'deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null"
    become: 'yes'
  - name: Update apt and install docker-ce
    apt:
      name: 
         - docker-ce
         - docker-ce-cli
         - containerd.io
         - docker-compose-plugin
      state: latest
      update_cache: true
    become: 'yes'
  - name: clone git
    git:
      repo: https://github.com/NaimAssoumani/Projets_Devops_flask
      dest: /home/vagrant/AppFlask
      version: preprod
      clone: yes
      update: no

  - name: docker compose
    shell: "cd AppFlask; docker compose down; docker compose up -d"
